<!--#include file="common.asp" -->
<%
header("indelibility", "我们不会忘记");
%>
<p>在进行软件介绍或测试中，许多专家和同行提出了很好的思路、建议或批评。这些都是我们的产品进一步完善和发展的动力。我们不会忘记这些无私提供其智慧和经验的同行，我们心怀感激，我们备受鼓舞，我们将更加努力！</p>
<table>
	<thead>
		<tr>
			<th scope="col">专家和同行</th>
			<th scope="col">工作单位</th>
			<th scope="col">被采纳的建议</th>
		</tr>
	</thead>
	<tr>
		<td>唐建明、杨飚、李立诚、单连玉</td>
		<td>西南局、吐哈油田、新疆局、胜利油田</td>
		<td>约束层析反演功能</td>
	</tr>
	<tr>
		<td>杨飚</td>
		<td>吐哈油田</td>
		<td>“初至波二次剩余静校正”概念的提出</td>
	</tr>
	<tr>
		<td>杨飚</td>
		<td>吐哈油田</td>
		<td>“无缝拼接”三维层析反演概念的提出</td>
	</tr>
	<tr>
		<td>李旭明</td>
		<td>青海研究院</td>
		<td>在初至拾取窗口中将初至时间连线显示</td>
	</tr>
	<tr>
		<td>杨飚</td>
		<td>吐哈油田</td>
		<td>确定三维高速顶界面的快捷方式</td>
	</tr>
	<tr>
		<td>杜尧树</td>
		<td>吐哈油田</td>
		<td>显示坐标变换信息</td>
	</tr>
	<tr>
		<td>董浩</td>
		<td>西南局</td>
		<td>在初至拾取窗口中，使用右键做删除</td>
	</tr>
	<tr>
		<td>王斌、黄玉静</td>
		<td>西南局</td>
		<td>静校正量输出cgg格式，并提供样本</td>
	</tr>
	<tr>
		<td>单连玉、兰益军</td>
		<td>胜利油田、bgp</td>
		<td>层析速度模型的“层状化”</td>
	</tr>
	<tr>
		<td>薛卫平、兰益军</td>
		<td>新疆局、bgp</td>
		<td>将静校正量按常规格式（8列）输出</td>
	</tr>
	<tr>
		<td>薛卫平</td>
		<td>新疆局</td>
		<td>速度模型可显示炮点或检波点的站号</td>
	</tr>
	<tr>	<td>蔡其新</td>
		<td>中原油田物探研究院</td>
		<td>对比两套静校正量的效果”</td>
        </tr>
	<tr>	<td>孟凡冰</td>
		<td>中原油田物探研究院</td>
		<td>输出CMP参考面</td>
        </tr>
</table>
<%
footer();
%>
