<!-- #include file="common.asp" -->
<!-- #include file="inc/function.asp" -->
<%
title="关于我们"
%>
<!-- #include file="header.asp" -->
<div id="bodier">
	<div id="content">
		<h2>关于网站</h2>
		<p>本站采用XHTML+CSS制作实现，未通过W3C的XHTML 1.0和CSS 2.0代码校验，目前遵循过渡型DOCTYPE。请使用IE6.0以上版本，最低800*600分辨率浏览以获得最佳浏览效果</p>
		<h2>站长介绍</h2>
		<p>MLTR中文站是两个在读大二学生在大一时联合创办的，他们一个在南方，一个在北方，因为共同的爱好，在网上结识为朋友，对于听着MLTR歌声成长至今的我们，把MLTR中文站做为自己的责任，克服了很多意想不到的困难，终于共同努力，携手合作，创办了MLTR中文站</p>
		<h3>Ryan</h3>
		<img src="images/other_ryan.jpg" alt="Ryan" />
		<ul>
			<li>本名：李泽言</li>
			<li>性别：Male</li>
			<li>出生地：湖南郴州</li>
			<li>现在居住地：寝室(在武汉念大学)</li>
			<li>生 日：1985/07/05</li>
			<li>血 型：O型</li>
			<li>QQ：42095356<a href="http://wpa.qq.com/msgrd?V=1&amp;Uin=42095356&amp;Site=MLTR中文站&amp;Menu=yes" rel="external"><img src="http://wpa.qq.com/pa?p=1:42095356:7" alt="点击这里给我发消息"></a></li>
			<li>MSN：ryanzone@hotmail.com</li>
			<li>E-mail：<a href="mailto:ryan@mltr.cn" class="email">ryan@mltr.cn</a></li>
		</ul>
		<h3>宇义</h3>
		<img src="images/other_scyui.jpg" alt="ScYui" />
		<ul>
			<li>本 名：李靖威</li>
			<li>网 名：宇义</li>
			<li>籍 贯：黑龙江</li>
			<li>居住地：天津市</li>
			<li>生 日：1985年10月20日</li>
			<li>QQ：88040404<a href="http://wpa.qq.com/msgrd?V=1&amp;Uin=88040404&amp;Site=MLTR中文站&amp;Menu=yes" rel="external"><img src="http://wpa.qq.com/pa?p=1:88040404:7" alt="点击这里给我发消息"></a></li>
			<li>MSN: ScYui@hotmail.com</li>
			<li>E'mail: <a href="mailto:scyui@mltr.cn" class="email">scyui@mltr.cn</a></li>
			<li>个人主页: www.Yuioo.com</li>
		</ul>
	</div>
</div>
<!-- #include file="footer.asp" -->