<!-- #include file="common.asp" -->
<!-- #include file="inc/function.asp" -->
<%
title="交换链接"
%>
<!-- #include file="header.asp" -->
<div id="bodier">
	<div id="ourlink">
		<h2>本站链接</h2>
<!-- #include file="inc/main_link.asp" -->
	</div>
	<div id="ourlogo">
		<h2>本站LOGO</h2>
		<img src="images/logo.gif" alt="MLTR中文站" class="show" />
		<p>将以下代码放入你的主页中，并发送邮件至<a href="mailto:webmaster@mltr.cn">webmaster@mltr.cn</a>，详细说明网站名称、简介、LOGO地址，我们会尽快做好你们的链接，谢谢。另外为保证速度本站链接的logo全部下载至本站服务器，若您更改了logo样式或更改了链接地址请发邮件通知我们，谢谢！</p>
		<code><pre>&lt;a href=&quot;http://www.mltr.cn&quot;&gt;&lt;img src=&quot;http://www.mltr.cn/images/logo.gif&quot; alt=&quot;MLTR中文站&quot; /&gt;&lt;/a&gt;</pre></code>
	</div>
</div>
<!-- #include file="footer.asp" -->